<!doctype html>
<html>
  <head>
    <title>{% block title %}Kothique Chaturbate Backend{% endblock %}</title>
    <link rel="shortcut icon" href="/assets/images/favicon.ico">
    <link rel="icon" sizes="16x16 32x32 64x64" href="/assets/images/favicon.ico">
    <link rel="icon" type="image/png" sizes="196x196" href="/assets/images/favicon-192.png">
    <link rel="icon" type="image/png" sizes="160x160" href="/assets/images/favicon-160.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/assets/images/favicon-96.png">
    <link rel="icon" type="image/png" sizes="64x64" href="/assets/images/favicon-64.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/images/favicon-32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/images/favicon-16.png">
    <link rel="apple-touch-icon" href="/assets/images/favicon-57.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/assets/images/favicon-114.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/assets/images/favicon-72.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/assets/images/favicon-144.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/assets/images/favicon-60.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/assets/images/favicon-120.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/assets/images/favicon-76.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/assets/images/favicon-152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/images/favicon-180.png">
    <meta name="msapplication-TileColor" content="#FFFFFF">
    <meta name="msapplication-TileImage" content="/assets/images/favicon-144.png">
    <meta name="msapplication-config" content="/assets/browserconfig.xml">

    <style>
      a {
        text-decoration: none;
        color: blue;
      }

      .title {
        font-weight: bold;
        font-size: 1.2rem;
        margin-bottom: 0.4rem;
      }
    </style>

    {% block head %}{% endblock %}
  </head>
  <body>
    {% block content %}
      <p>Missing content!</p>
    {% endblock %}
  </body>
</html>
