<!doctype html>
<html>
  <head>
    <title>{% block title %}Kothique Chaturbate Backend{% endblock %}</title>
    <style>
      a {
        text-decoration: none;
        color: blue;
      }

      .title {
        font-weight: bold;
        font-size: 1.2rem;
        margin-bottom: 0.4rem;
      }
    </style>

    {% block head %}{% endblock %}
  </head>
  <body>
    {% block content %}
      <p>Missing content!</p>
    {% endblock %}
  </body>
</html>
